project:
  type: website
website:
  title: "Numerical semigroups course Scuola Superiore di Catania"
  search: false
  site-url: https://numerical-semigroups.github.io/SSC-Semigroups/
  repo-url: https://github.com/numerical-semigroups/SSC-Semigroups
  issue-url: https://github.com/numerical-semigroups/SSC-Semigroups/issues
  navbar:
    right:
      - icon: github
        href: https://github.com/numerical-semigroups/SSC-Semigroups
        aria-label: GitHub

  sidebar: 
    style: "docked"
    footer: Rendered with [Quarto](https://quarto.org/)
    contents:
      - text: "First steps in GAP"
        href: "1-First steps GAP.ipynb"
      - text: "Numerical semigroups: notable elements"
        href: "2-numercalsgps-first-session.ipynb"
      - text: "Pseudo-Frobenius numbers and families"
        href: "3-numericalsgps-second-lesson.ipynb"
      - text: "Gluings, Hilbert series, minimal presentations"
        href: "4-numercalsgps-third-session.ipynb"
      - text: "Minimal presentations and binomial ideals, complete intersections"
        href: "5-numercalsgps-fourth-session.ipynb"
      - text: "Non-unique factorization invariants, primality, divisors"
        href: "6-numericalsgps-fifth-session.ipynb"
      - text: "Ideals of numerical semigroups"
        href: "7-numericalsgps-seventh-session.ipynb"
      - text: "Codes with GUAVA"
        href: "gap-guava.md"

format:
  html:
    theme: cosmo
